version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: "Asia/Shanghai"
    target-branch: "dev"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: "Asia/Shanghai"
    target-branch: "dev"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: "Asia/Shanghai"
    target-branch: "dev"
