name: Android 格式检查

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "package.json"
      - "yarn.lock"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "package.json"
      - "yarn.lock"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 格式检查
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: chmod +x gradlew && ./gradlew spotlessCheck
