name: Android 构建

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 构建并签名
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: chmod +x gradlew && ./gradlew assembleRelease

      - name: 重命名 APK
        run: python3 ci.py rename

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/release

      - name: 发送 APK 到企业微信
        uses: MeanZhang/wecom-group-robot@v1.2
        with:
          key: ${{ secrets.KEY }}
          msgtype: "file"
          content: app/build/outputs/apk/release/*.apk
