name: Android CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 检查并构建
        run: |
          chmod +x gradlew && ./gradlew spotlessCheck assembleRelease

      - name: APK 签名
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: 重命名 APK
        run: mv ${{ env.SIGNED_RELEASE_FILE }} '${{ secrets.APP_NAME }}.apk'

      - name: 上传 APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: ${{ secrets.APP_NAME }}.apk

      - name: 发送 APK 到企业微信
        uses: MeanZhang/wecom-group-robot@v1.1
        with:
          key: ${{ secrets.KEY }}
          msgtype: "file"
          content: "${{ secrets.APP_NAME }}.apk"
