name: Docs Build Check

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "docs/**"
      - "package.json"
      - "yarn.lock"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
          cache: "yarn"

      - name: build
        run: yarn && yarn docs:build
